### PR TITLE
Fix id uniqueness

### PR DESCRIPTION
**Pull request by oren-zohar**
### Summary of your changes
Rule ID was based on the rule name + benchmark id. I found out that in some benchmarks they have rules which share the same name, which led to duplicate rule ID. this will change the way. we calculate the rule id based on the benchmark + rule name + rule number.

### Checklist

- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added the necessary README/documentation (if appropriate)

> **Note** Make sure to bump cloudbeat [`version/policy.go`](https://github.com/elastic/cloudbeat/blob/main/version/policy.go#L20) after merging this PR and drafting a new release.

### CODE REVIEW

**Review by olegsu — APPROVED** [review]
Why using UUID without any ns is not good enough?

**Comment by oren-zohar** [comment]
> Why using UUID without any ns is not good enough?

It's a required field for [uuid5](https://docs.python.org/3/library/uuid.html#uuid.uuid5)

**Comment by olegsu** [comment]
> > Why using UUID without any ns is not good enough?
> 
> It's a required field for [uuid5](https://docs.python.org/3/library/uuid.html#uuid.uuid5)

What about uuidv4? https://generate-uuid.com/which-uuid-version-should-you-use

**Comment by oren-zohar** [comment]
> > > Why using UUID without any ns is not good enough?
> > 
> > 
> > It's a required field for [uuid5](https://docs.python.org/3/library/uuid.html#uuid.uuid5)
> 
> What about uuidv4? https://generate-uuid.com/which-uuid-version-should-you-use

Yes, it's definitely possible, but the original idea was to go with the same version as the old script, so we won't edit the UUIDs, although in the end, we ended up with a new UUID to fix this bug. going to UUIDv4 will result in new UUIDs? if so it will require new PR to /integrations to update rules templates. Is there an added value of abandoning the namespace that you think is crucial?

**Comment by olegsu** [comment]
> > > > Why using UUID without any ns is not good enough?
> > > 
> > > 
> > > It's a required field for [uuid5](https://docs.python.org/3/library/uuid.html#uuid.uuid5)
> > 
> > 
> > What about uuidv4? https://generate-uuid.com/which-uuid-version-should-you-use
> 
> Yes, it's definitely possible, but the original idea was to go with the same version as the old script, so we won't edit the UUIDs, although in the end, we ended up with a new UUID to fix this bug. going to UUIDv4 will result in new UUIDs? if so it will require new PR to /integrations to update rules templates. Is there an added value of abandoning the namespace that you think is crucial?

I don't see any reason that it would be crucial. Just out of curiosity, I thought maybe we had a reason to choose v5 over v4.
LGTM 👍

**Pull request merged**
